=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hundsun.com/ooas/config"
    xmlns="http://www.hundsun.com/ooas/config" elementFormDefault="qualified">

    <xs:element name="config" type="config">
    </xs:element>

    <xs:complexType name="option">
        <xs:attribute name="value" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="related" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="validator">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="option" type="option"></xs:element>
        </xs:choice>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="select"></xs:enumeration>
                    <xs:enumeration value="radio"></xs:enumeration>
                    <xs:enumeration value="checkbox"></xs:enumeration>
                    <xs:enumeration value="required"></xs:enumeration>
                    <xs:enumeration value="url"></xs:enumeration>
                    <xs:enumeration value="email"></xs:enumeration>
                    <xs:enumeration value="date"></xs:enumeration>
                    <xs:enumeration value="digits"></xs:enumeration>
                    <xs:enumeration value="equalTo"></xs:enumeration>
                    <xs:enumeration value="extension"></xs:enumeration>
                    <xs:enumeration value="maxlength"></xs:enumeration>
                    <xs:enumeration value="minlength"></xs:enumeration>
                    <xs:enumeration value="rangelength"></xs:enumeration>
                    <xs:enumeration value="range"></xs:enumeration>
                    <xs:enumeration value="max"></xs:enumeration>
                    <xs:enumeration value="min"></xs:enumeration>
                    <xs:enumeration value="pattern"></xs:enumeration>
                    <xs:enumeration value="ipv4"></xs:enumeration>
                    <xs:enumeration value="ipv6"></xs:enumeration>
                    <xs:enumeration value="ip"></xs:enumeration>
                    <xs:enumeration value="domain"></xs:enumeration>
                    <xs:enumeration value="host"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="value" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="property">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="default" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="display">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                    <xs:enumeration value="hide"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="group">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
            <xs:element ref="property"></xs:element>
            <xs:element ref="group"></xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="display">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                    <xs:enumeration value="hide"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="validator" type="validator"></xs:element>
    <xs:element name="property" type="property"></xs:element>
    <xs:element name="group" type="group"></xs:element>

    <xs:complexType name="config">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
            <xs:element ref="property"></xs:element>
            <xs:element ref="group"></xs:element>
        </xs:choice>
    </xs:complexType>

</xs:schema>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/counter/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">
	<group name="default" label="柜台配置">
        <property name="interface_oos_counter_user_bean_ref" label="网上开户用户柜台接口" default="oosHSUserCounter">
            <validator type="select">
                <option value="oosHSUserCounter" label="恒生用户柜台" related="ifs"></option>
                <option value="oosCtsecUserCounter" label="财通用户柜台" description="唯一性校验通过数据中心查询校验" related="ifs"></option>
                <option value="oosLiveBosUserCounter" label="顶点用户柜台" related="livebos"></option>
                <option value="oosKospUserCounter" label="金证资产交易系统用户柜台" related="kingdom_kosp"></option>
                <option value="oosHSEtsUserCounter" label="恒生基金直销交易系统用户柜台" related="ets"></option>
            </validator>
        </property>

        <property name="interface_oos_counter_teller_bean_ref" label="网上开户柜员柜台接口" default="oosHSTellerCounter">
            <validator type="select">
                <option value="oosHSTellerCounter" label="恒生柜员柜台" related="ifs"></option>               
                <option value="oosLiveBosTellerCounter" label="顶点柜员柜台" related="livebos"></option>
                <option value="oosKospTellerCounter" label="金证资产交易系统柜员柜台" related="kingdom_kosp"></option>
                <option value="oosHSEtsTellerCounter" label="恒生基金直销交易系统柜员柜台" related="ets"></option>
            </validator>
        </property>

        <property name="interface_obs_counter_bean_ref" label="网厅柜台接口" default="obsHSCounter">
            <validator type="select">
                <option value="obsHSCounter" label="恒生柜台" related="ifs"></option>               
                <option value="obsLiveBosCounter" label="顶点柜台" related="livebos"></option>     
            </validator>
        </property>
        <!-- 网厅多柜台存在时，次要柜台的接口 -->
         <property name="interface_obs_many_counter_bean_ref" label="网厅次要柜台接口" default="obsHSManyCounter">
            <validator type="select">
            	<option value="obsHSManyCounter" label="恒生柜台" related="ifs"></option>
                <option value="obsLiveBosManyCounter" label="顶点柜台" related="livebos"></option>
            </validator>
        </property>
    </group>
    <group id="ifs">
        <property name="ifs_run_mode" label="IFS运行模式" default="run">
            <validator type="radio">
                <option value="run" label="生产模式" related="ifs_settings" />
                <option value="debug" label="调试模式" />
            </validator>
        </property>

        <group id="ifs_settings">
            <property name="ifs_webservice_url_host" label="连接地址主机" default="" description="连接地址IP或域名">
                <validator type="required" />
                <validator type="host" />
            </property>
            <property name="ifs_webservice_url_port" label="连接地址端口" default="8080">
                <validator type="required" />
                <validator type="range" value="[1,65535]" />
            </property>
            <property name="ifs_webservice_url_serviceContext" label="连接地址服务路径" default="/WAserver"
                description="连接地址服务路径，例如连接地址为：http://192.168.54.168:8080/WAserver，则服务路径为/WAserver">
                <validator type="required" />
                <validator type="pattern" value="^/.+" />
            </property>

            <property name="ifs_webservice_url_trade_host" label="交易子系统连接地址主机" default="" description="交易子系统连接地址IP或域名">
                <validator type="required" />
                <validator type="host" />
            </property>
            <property name="ifs_webservice_url_trade_port" label="交易子系统连接地址端口" default="8080">
                <validator type="required" />
                <validator type="range" value="[1,65535]" />
            </property>
            <property name="ifs_webservice_url_trade_serviceContext" label="交易子系统连接地址服务路径" default="/WAserver"
                description="交易子系统连接地址服务路径，例如连接地址为：http://192.168.54.168:8080/WAserver，则服务路径为/WAserver">
                <validator type="required" />
                <validator type="pattern" value="^/.+" />
            </property>

            <property name="ifs_operator_branch_no" label="操作员(柜员)营业部编号" default="">
                <validator type="required" />
            </property>
            <property name="ifs_operator_no" label="操作员(柜员)编号" default="">
                <validator type="required" />
            </property>
            <property name="ifs_operator_pwd" id="password" label="操作员(柜员)密码" default="">
                <validator type="required" />
            </property>
            <property name="ifs_operator_station" label="操作员站点" default="">
                <validator type="required" />
            </property>
            <property name="ifs_operator_busin_owner" label="客户关系人" default=""
                description="客户关系人（中金补丁），需与与IFS-broker_config.xml匹配">
            </property>
            <property name="ifs_account_unity" label="IFS接口是否支持统一账户" default="0"
                description="0-不支持， 1-支持">
            </property>
        </group>
    </group>
    <group id="t2sdk">
        <property name="t2_host" label="T2连接地址主机" default="" description="T2连接地址IP或域名">
            <validator type="required" />
            <validator type="host" />
        </property>
        <property name="t2_port" label="T2连接地址端口" default="18001">
            <validator type="required" />
            <validator type="range" value="[1,65535]" />
        </property>
        <property name="t2_license_url" label="T2 License地址" default="classpath:hst2_client_license.dat" description="配置License地址，默认classpath:hst2_client_license.dat则在WEB-INF/classes目录，也可以配置绝对路径，如/usr/local/runtime_config_root/hst2_client_license.dat">
            <validator type="required" />
        </property>
    </group>
     <group id="livebos">
     	<property name="livebos_userid" label="顶点CIF webservice服务用户ID" default="123" description="">
            <validator type="required" />
        </property>
     	<property name="livebos_user" label="顶点CIF webservice服务用户名" default="webuser" description="">
            <validator type="required" />
        </property>
        <property name="livebos_password" id="password" label="顶点CIF webservice服务密码" default="888888">
            <validator type="required" />
        </property>
        <property name="livebos_service_url" label="顶点CIF webservice地址" default="http://10.10.16.226:8020/service/LBEBusiness?wsdl">
            <validator type="required" />
        </property>
        
        <property name="crh_fixapi_ip" label="顶点fix接口转发程序IP" default="" description="">
            <validator type="required" />
            <validator type="host" />
        </property>
        <property name="crh_fixapi_port" label="顶点fix接口转发程序端口" default="6010">
            <validator type="required" />
            <validator type="range" value="[1,65535]" />
        </property>
        
    </group>
    <group id="kingdom_kosp">
        <property name="kosp_oauth2_clientid" label="OAUTH2服务器APP_key" default="" description="OAUTH2服务器供应商提供给商家的APP_key">
            <validator type="required" />
        </property>
        <property name="kosp_oauth2_clientSecret" label="OAUTH2服务器APP_Secret" default="" description="OAUTH2服务器供应商提供给商家的APP_Secret">
            <validator type="required" />
        </property>
        <property name="kosp_oauth2_url" label="API的首部地址" default="http://192.168.1.102:8991/koauth2/" description="">
            <validator type="required" />
            <validator type="url" />
        </property>
        <property name="kosp_oauth2_version" label="KOAUTH2版本信息" default="V2.0" description="">
            <validator type="required" />
        </property>
    </group>
    <group id="ets">
        <property name="ets_webservice_url" label="ETS服务接口地址" default="ets.webservice.url=172.15.1.161:7100/openapi/fundbusrestful" description="">
            <validator type="required" />
            <validator type="url" />
        </property>
        <property name="ets_partner_id" label="ETS银行渠道列表id" default="" description="ETS银行渠道列表id">
            <validator type="required" />
        </property>
    </group>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/sc/config_connection.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	
	<group id="mall_connection" label="商城通讯配置" display="true">
		<property name="crh_connection_timeout" label="与中台接口通讯连接超时时间"
			default="60" description="单位秒,默认60秒">
		</property>
		<property name="crh_so_timeout" label="与中台接口通讯提交请求超时时间"
			default="60" description="单位秒，默认60秒">
		</property>
		<property name="crh_cookie_name" label="中台WebService请求cookie键值格式"
			default="" description="">
		</property>
		<property name="crh_cookie_path" label="中台WebService请求cookie路径"
			default="" description="">
		</property>
		<property name="sisap_cookie_domain" label="中台WebService请求cookie作用域"
			default="" description="">
			<validator type="required" />
            <validator type="host" />
		</property>
		<property name="sisap_webservice_url" label="中台WebService接口地址"
			default="" description="">
		</property>
		<property name="wt_cookie_domain" label="网厅域名"
			default="" description="">
			<validator type="required" />
            <validator type="host" />
		</property>
	</group>

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/sjwt/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">
	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="true"></option>
		<option label="关" value="false"></option>
	</validator>
	<validator id="visible_checkbox" type="checkbox">
		<option label="显示" value="visible"></option>
		<option label="隐藏" value="invisible"></option>
	</validator>
	<validator id="apply_type" type="radio">
		<option label="不验证" value="0"></option>
		<option label="身份证验证" value="1"></option>
		<option label="手机验证码验证" value="2"></option>
	</validator>



	<group id="sjwt_config" label="手机网厅配置" display="true">
		<property name="sjwt_template" label="券商个性化版本"
		description="选择券商，同时会设置券商简称, 此配置会影响样式文件的调用目录">
			<validator type="select">
				<option value="" label="标准版网厅"/>
				<option value="cf" label="财富证券" />
			</validator>
		</property>
		<property name="sjwt_resource_usecache" label="是否进行公共数据缓存处理"
			default="true" description="涉及缓存内容有:风险测评题库,协议">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	
		<property name="sjwt_resource_cache_expires" label="资源缓存失效时间"
			default="86400000" description="资源缓存失效时间,单位为毫秒" />
	
		<property name="agreement_title_display" label="协议显示时,是否展示协议标题"
			default="invisible" description="协议显示时,是否展示协议标题,协议内容中已配置了标题内容,防止显示冲突">
			<validator type="checkbox" ref="visible_checkbox"></validator>
		</property>
		<property name="risk_question_no_display" label="风险测评题目序号是否显示"
			default="invisible" description="风险测评显示题目序号(例如A,B,C)是否显示">
			<validator type="checkbox" ref="visible_checkbox"></validator>
		</property>
		<property name="sjwt_register_url" label="手机开户访问地址"
			 description="配置后可在登陆页面点注册跳转到手机开户" />
		<property name="anychat_server_url" label="anychat视频的外网地址"
			 description="anychat视频的外网地址,提供手机客户端连接" />
		<property name="anychat_server_port" label="anychat视频的外网端口"
			 default="8906" description="anychat视频的外网端口,提供手机客户端连接,一般情况下是8906" />
		<property name="sjwt_cert_apply_type" label="自建证书申请,安装验证方式"
			 default="0" description="自建证书申请,安装验证方式 0为不验证 1为输入身份证验证 2为手机验证码验证">
			 <validator type="checkbox" ref="apply_type"></validator>
		</property>
		<property name="sjwt_reset_password_communication_display" label="重置密码是否显示通讯密码"
			default="invisible" description="重置密码是否显示通讯密码">
			<validator type="checkbox" ref="visible_checkbox"></validator>
		</property>
		
			 
	</group>

	<group id="sjwt_authorize" label="手机网厅授权码" display="true">
		<property name="sjwt_business_key" label="手机网厅授权码"
			default=""  />
	</group>

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/wt/config_account.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

<!-- 理财产品账户类配置 -->
	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="judge_checkbox2" type="checkbox">
		<option label="需要" value="1"></option>
		<option label="不需要" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	
     <group id="funds" label="基金配置" display="true">
		<property name="fund_account_sign_every_agreement" label="开放式基金签署协议是否每个基金都签署协议"
			default="0" description="开放式基金签署协议是否每个基金都签署协议">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="openfundacct_check_risk" label="开放式基金开通是否要检查风险评测"
			default="1" description="开放式基金开通是否要检查风险评测做过或者未过期">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
		<property name="openfundacctfirst_check_risk" label="开放式基金首次开通是否必须先进行风险评测 "
			default="0" description="开放式基金首次开通是否必须先进行风险评测  1需要，0不需要。默认0">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
	</group>
	
	
	<group id="product" label="理财和资管产品配置" display="true">
		<property name="zg_ta" label="支持开通的资管产品TA" default="98"
			description="该配置项配置为，网厅支持资管产品的TA代码，多个用#隔开，但必须保证每个都能在柜台查询到" />
		<property name="wt_isneed_otc_item" label="理财产品协议签订模块是否要包含OTC产品" default="0" description="理财产品协议签订模块是否要进行OTC产品的查询和显示 ">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	</group>
	
	<group id="otc" label="OTC配置" display="true">
		<property name="otc_min_risk_level" label="开通OTC账户最低风险等级" default="0" description="OTC风险评测必须满足一定的等级才允许开通，默认等级是 0  (@version:3.4.1;@auth:gaowx)">
		</property>
		<property name="otc_min_risk_score" label="OTC在线评测必须满足一定的分数才允许开通" default="0" description="OTC在线评测必须满足一定的分数才允许开通，默认分数是 60.目前只有湘财需要在线测评">
		</property>
		<property name="otc_open_sign_agreement" label="开通OTC账户是否需要签署协议" default="1" description="OTC账户开通是否需要签署协议，0不需要，1需要。默认1.">
		<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>		
	</group>
	
	<group id="funcbankmacct" label="银行理财配置" display="true">
		<property name="product_funcbankmacct_risk_flag" label="银行理财账户首次开户是否去临柜风险评测" default="0" description="首次开户是否去临柜风险评测， 1：去柜台做，0：网厅做.默认0 ">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
		<property name="wt_funbankopen_risk_date" label="银行理财账户开户，风险评测过期时间的长度" default="3"
			description="银行理财账户开户，风险评测过期时间的长度。比如：做了评测“3”年才算过期,“年”为单位。目前暂时不用" />
	</group>
	

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/sc/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	
	<group id="mall" label="商城配置" display="true">
		<property name="security_name" label="券商名称"
			default="" description="此名称将全局显示在各网页文字部分">
		</property>
		<property name="security_short" label="券商简称"
			default="" description="">
		</property>
		<property name="webAddr" label="商城地址"
			default="" description="">
		</property>
		<property name="scWebAddr" label="商城地址"
			default="" description="">
		</property>
		<property name="wt_webaddr" label="网厅地址"
			default="" description="">
		</property>
		<property name="staticResourcesAddr" label="静态资源地址"
			default="" description="">
		</property>
		<property name="resource_path" label="商城版本"
			default="ctzqnew" description="">
			<validator type="select">
				<option value="ctzq" label="财通证券" />
				<option value="ctzqnew" label="财通证券新版" />
				<option value="xczq" label="湘财证券" />
			</validator>
		</property>
		<property name="sec_name" label="券商官网名称"
			default="" description="">
		</property>
		<property name="sec_official_website" label="券商官网"
			default="" description="">
		</property>
		<property name="sec_open_account_website" label="券商开户网站"
			default="" description="">
		</property>
		<property name="sec_simple_open_account_website" label="券商简易开户网站"
			default="" description="">
		</property>
		<property name="sec_software_download_website" label="软件下载连接"
			default="" description="">
		</property>
		<property name="cookie_domain" label="域名"
			default="" description="">
		</property>
		<property name="cookie_version" label="cookie版本"
			default="" description="">
		</property>
		<property name="cookie_aes_key" label="cookie对称加密KEY"
			default="" description="16个数字，大或小写英文，符号组成（必配）">
		</property>
		<property name="cookie_aes_iv" label="cookie对称加密向量"
			default="" description="16个数字（必配）">
		</property>
		<property name="middle_connect_model" label="中台连接运行方式"
			default="" description="（run / debug）">
		</property>
		<property name="video_queue_root_inner" label="视频队列服务内网根地址"
			default="" description="（必配）">
		</property>
		<property name="video_default_branch_no" label="提供视频服务的默认营业部编号"
			default="" description="不输入时，视频服务为客户所属的营业部">
		</property>
		<property name="op_entrust_way" label="商城委托方式"
			default="" description="">
		</property>
		<property name="sc_gw" label="商城头部的官网链接是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="sc_rjxz" label="商城头部的软件下载链接是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="zqkh" label="商城头部的证券开户链接是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="lckh" label="商城头部的理财开户链接是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="sc_zglc" label="商城头部的资管理财产品下拉菜单是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="sc_jjlc" label="商城头部的基金理财产品下拉菜单是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="sc_otclc" label="商城头部的otc理财产品下拉菜单是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="sc_banklc" label="商城头部的银行理财产品下拉菜单是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="sc_need_yykh" label="登录框预约开户按钮是否显示"
			default="1" description="">
			<validator type="checkbox" ref="display_checkbox"></validator>
		</property>
		<property name="sc_need_yykhUrl" label="登录框预约开户链接地址"
			default="" description="">
		</property>
	</group>

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/store/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

    <group id="upload">
        <property name="server_staticfile_cdn_server" label="上传文件浏览服务主机地址" default=""
            description="上传文件浏览服务主机地址，最后不要有/，如http://static.cairenhui.com">
            <validator type="required" />
            <validator type="pattern" value="[^/]$" />
        </property>
        <property name="server_staticfile_cdn_serviceContext" label="上传文件浏览服务路径" default=""
            description="上传文件浏览服务路径，如果上传文件浏览服务的完整URL为http://static.cairenhui.com/uploadFiles，则此处填写/uploadFiles">
            <validator type="required" />
            <validator type="pattern" value="^/.+" />
        </property>
        <property name="homedir_uploader_cdn" label="上传文件服务器本地路径" default="">
            <validator type="required" />
        </property>
        <property name="homedir_uploader_cdn_classification" label="上传文件是否需要分类存储" default="0" description="此处配置为需要时，将在[上传文件服务器本地路径]下进行分类（video，image）">
            <validator type="checkbox">
               <option label="是" value="1" related="upload_classification"></option>
        	   <option label="否" value="0"></option>
            </validator>
        </property>
        <group id="upload_classification">
        	<property name="homedir_video_uploader_cdn" label="视频文件本地文件夹（路径）名" default="video" description="最终路径:[上传文件服务器本地路径][视频文件本地文件夹（路径）名]">
            	<validator type="required" />
        	</property>
        	<property name="homedir_image_uploader_cdn" label="图片文件本地文件夹（路径）名" default="image" description="最终路径:[上传文件服务器本地路径][图片文件本地文件夹（路径）名]">
            	<validator type="required" />
        	</property>
        </group>
        <property name="homedir_uploader_file" label="上传协议文件服务器本地路径" default="D:\\doc\\uploadObsFiles">
            <validator type="required" />
        </property> 
        <property name="homedir_down_adress" label="下载视频取视频播放时长" default="C:\\var">
            <validator type="required" />
        </property> 
        <property name="middle_cluster_nodes" label="中台集群其余节点地址" default="" description="不包括当前节点，示例:middle.cluster.nodes=http://localhost:8888/xpe-sisap-arch/,http://localhost:9999/xpe-sisap-arch/">
        </property>
        <property name="middle_cluster_count" label="中台集群最多同步次数" default="24" description="只支持正整数">
        </property>
        <property name="middle_cluster_interval" label="中台集群同步时间间隔" default="1" description="只支持正整数（单位：小时）">
        </property>
        
    </group>
</config>
