=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hundsun.com/ooas/config"
    xmlns="http://www.hundsun.com/ooas/config" elementFormDefault="qualified">

    <xs:element name="config" type="config">
    </xs:element>

    <xs:complexType name="option">
        <xs:attribute name="value" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="related" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="validator">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="option" type="option"></xs:element>
        </xs:choice>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="select"></xs:enumeration>
                    <xs:enumeration value="radio"></xs:enumeration>
                    <xs:enumeration value="checkbox"></xs:enumeration>
                    <xs:enumeration value="required"></xs:enumeration>
                    <xs:enumeration value="url"></xs:enumeration>
                    <xs:enumeration value="email"></xs:enumeration>
                    <xs:enumeration value="date"></xs:enumeration>
                    <xs:enumeration value="digits"></xs:enumeration>
                    <xs:enumeration value="equalTo"></xs:enumeration>
                    <xs:enumeration value="extension"></xs:enumeration>
                    <xs:enumeration value="maxlength"></xs:enumeration>
                    <xs:enumeration value="minlength"></xs:enumeration>
                    <xs:enumeration value="rangelength"></xs:enumeration>
                    <xs:enumeration value="range"></xs:enumeration>
                    <xs:enumeration value="max"></xs:enumeration>
                    <xs:enumeration value="min"></xs:enumeration>
                    <xs:enumeration value="pattern"></xs:enumeration>
                    <xs:enumeration value="ipv4"></xs:enumeration>
                    <xs:enumeration value="ipv6"></xs:enumeration>
                    <xs:enumeration value="ip"></xs:enumeration>
                    <xs:enumeration value="domain"></xs:enumeration>
                    <xs:enumeration value="host"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="value" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="property">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="default" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="display">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                    <xs:enumeration value="hide"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="group">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
            <xs:element ref="property"></xs:element>
            <xs:element ref="group"></xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="display">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                    <xs:enumeration value="hide"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="validator" type="validator"></xs:element>
    <xs:element name="property" type="property"></xs:element>
    <xs:element name="group" type="group"></xs:element>

    <xs:complexType name="config">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
            <xs:element ref="property"></xs:element>
            <xs:element ref="group"></xs:element>
        </xs:choice>
    </xs:complexType>

</xs:schema>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/wt/config_cert.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

<!-- 网厅公共模块配置修改（高伟星）开始 -->
	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="judge_checkbox2" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	<validator id="visible_checkbox" type="checkbox">
		<option label="显示" value="visible"></option>
		<option label="隐藏" value="invisible"></option>
	</validator>
	
	<group id="cert" label="证书配置" display="true">
		<property name="ca_interface_bean" label="CA证书" default="itrus"
			description="CA证书接口方式">
			<validator type="select">
				<option value="itrus" label="天威CA" />
				<option value="csdcca" label="直连中登CA" />
				<option value="hscsdcca" label="恒生T2代理CA服务" />
				<option value="htcsdcca" label="海通代理CA服务" />
				<option value="hnca" label="河南CA" />
			</validator>
		</property>
		<property name="display_cert_item" label="网厅支持的证书" default="zd"
			description="">
			<validator type="select">
				<option value="" label="自建中登都支持" />
				<option value="zd" label="仅支持中登" />
				<option value="zj" label="仅支持自建" />
			</validator>
		</property>
		
		<property name="zd_cert_apply_need_sm" label="中登证书申请是否需要屏蔽短信验证步骤"
			default="1" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		
		<property name="zj_cert_apply_need_sms" label="自建证书申请是否需要屏蔽短信验证步骤"
			default="1" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>

		<property name="wt_first_zj_cert_need_uploadpic" label="自建证书第一次申请需要上传照片"
			default="1" description="">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
	</group>

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/wt/config_stockAccount.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="judge_checkbox2" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	<validator id="visible_checkbox" type="checkbox">
		<option label="显示" value="visible"></option>
		<option label="隐藏" value="invisible"></option>
	</validator>
	
	<group id="stock" label="证券账户配置" display="true">
		<property name="wt_show_exchange_traded_funds" label="证券账户是否显示场内基金"
			default="1" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="wt_show_stock_designated" label="证券账户是否显示指定交易"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="wt_take_stock_need_check" label="证券账户下挂是否需要审核"
			default="0" description="默认不需要">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="wt_open_stock_need_check" label="证券账户新开是否需要审核"
			default="0" description="默认不需要">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<!-- <property name="wt_stock_take_mode" label="证券账户下挂可多选模式"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property> -->
		<property name="wt_stock_accept_open_count_sz" label="证券账户允许用户开立的深圳A股账户个数"
			default="1" description="">
		</property>
		<property name="wt_stock_accept_open_count_sh" label="证券账户允许用户开立的上海A股账户个数"
			default="1" description="">
		</property>
		<property name="wt_stock_accept_take_count_sz" label="证券账户允许用户下挂的深圳A股账户个数"
			default="1" description="">
		</property>
		<property name="wt_stock_accept_take_count_sh" label="证券账户允许用户下挂的上海A股账户个数"
			default="1" description="">
		</property>
		
		<property name="wt_stock_need_submit" label="网厅是否同步证券账户到金网"
			default="0" description="只有中金需要   默认不同步">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	</group>

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/redis/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

    <group id="redis">
        <property name="redis_host" label="redis主机" default="127.0.0.1" description="redis IP或域名">
            <validator type="required" />
            <validator type="host" />
        </property>
        <property name="redis_port" label="redis端口" default="26379">
            <validator type="required" />
            <validator type="range" value="[1,65535]" />
        </property>
    </group>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/ccprest/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">
	<property name="interface_voice_bean_ref" label="语音验证码实现"
		default="demoVoiceServiceImpl">
		<validator type="select">
			<option value="demoVoiceServiceImpl" label="不发送语音验证码"></option>
			<option value="xnzqVoiceServiceImpl" label="西南证券语音验证码"
				related="voice_basic,xnzqset"></option>
			<option value="rlytVoiceServiceImpl" label="容联易通语音验证码"
				related="voice_basic,ccprest"></option>
			<option value="bwVoiceServiceImpl" label="百悟语音验证码"
				related="voice_basic,baiwuset"></option>
		</validator>
	</property>
	<group id="voice_basic" display="false">
		<property name="voice_run_model" label="语音验证码运行模式" default="run">
			<validator type="radio">
				<option value="run" label="生产" />
				<option value="debug" label="调试" />
			</validator>
		</property>
		<property name="voice_test_mobile" label="语音验证码测试号码" default=""
			description="语音验证码测试号码, 如不为空则所有语音验证码均发送至设置手机号码">
		</property>
	</group>
	<group id="xnzqset" display="false">
		<property name="xnzq_url" label="语音验证码接口地址" default=""
			description="语音验证码服务URL或语音验证码数据库URL">
			<validator type="required" />
		</property>
		<property name="xnzq_user" label="语音验证码服务使用帐号" default="">
			<validator type="required" />
		</property>
		<property name="xnzq_user_pwd" id="password" label="语音验证码服务使用密码"
			default="">
		</property>
	</group>
	<group id="baiwuset" display="false">
		<property name="baiwu_url" label="访问地址" default=""
			description="">
			<validator type="required" />
		</property>
		<property name="baiwu_accountSid" label="企业账号" default=""
			description="">
			<validator type="required" />
		</property>
		<property name="baiwu_passwd" label="密码" default=""
			description="">
			<validator type="required" />
		</property>
		<property name="baiwu_serviceCode" label="业务代码" default=""
			description="">
			<validator type="required" />
		</property>
		<property name="baiwu_callNumber" label="主叫号" default=""
			description="">
			<validator type="required" />
		</property>

	</group>

	<group id="ccprest" label="语音验证码配置">
		<property name="ccprest_url" label="服务器地址" default="sandboxapp.cloopen.com">
			<validator type="required" />
		</property>
		<property name="ccprest_port" label="服务器端口" default="8883">
			<validator type="required" />
			<validator type="range" value="[1,65535]" />
		</property>
		<property name="ccprest_accountSid" label="主帐号名称"
			default="aaf98f89490d8cf501491818085c06ae">
			<validator type="required" />
		</property>
		<property name="ccprest_accountToken" label="主帐号令牌"
			default="9a033fa8bc1f487ab04176a189f90196">
			<validator type="required" />
		</property>
		<property name="ccprest_AppId" label="应用ID"
			default="8a48b55148fe48600149182438f11091">
			<validator type="required" />
		</property>
		<property name="ccprest_showMobile" label="来电显示号码" default="400400">
			<validator type="required" />
		</property>
		<property name="ccprest_times" label="语音提示次数" default="1">
			<validator type="required" />
			<validator type="range" value="[1,999999999]" />
		</property>
	</group>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/wt/config_ht.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="judge_checkbox2" type="checkbox">
		<option label="需要" value="1"></option>
		<option label="不需要" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	
     <group id="funds" label="证书配置" display="true">
		<property name="zd_cert_need_verify" label="中登证书申请是否需要颁发步骤"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		
		<property name="zj_cert_need_verify" label="自建证书申请是否需要颁发步骤"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	</group>
	
	
	<group id="product" label="公安认证" display="true">
		<property name="wt_pwd_reset_need_ga_verify" label="网厅密码重置视频步骤，后台是否需要公安认证"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	</group>
	
	<group id="margin_ht" label="后台融资融券配置" display="true">
		<property name="margin_backend_editIdentityInfo" label="后台客服接到的融资融券视频，是否可以修改用户资料"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	</group>
	<group id="importsh_ht" label="后台重要资料审核发送短信内容" display="true">
		<property name="sms_important_data_modificationt" label="配置内容为发送，不配置为不发送"
			default="" description="">
		</property>
	</group>

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/arch/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

    <group id="archive_config" label="档案平台配置">
        <property name="archive_audit_auditlevel" label="档案审核级别" default="0" description="档案审核级别,0为不审核,1为审核,2为复核,包括审核,主二级审核">
        </property>
        <property name="archive_isOnTag" label="是否是外挂采集" default="0" description="是否是外挂采集">
        	<validator type="checkbox">
                <option label="是" value="1"></option>
                <option label="否" value="0"></option>
          	</validator>
        </property>
    </group>
    <group id="sandbox_config" label="档案沙箱配置">
        <property name="sandbox_ishavecallback" label="flash加载时是否调用回调函数" default="1" description="flash加载时是否调用回调函数，1为调用，0为不调用">
        </property>
    </group>
    <group id="nas_config" label="nas账号配置">
    	<property name="nas_host" label="nas服务器地址" default="" description="nas服务器地址">
        </property>
        <property name="nas_username" label="nas服务器用户名" default="" description="nas服务器用户名">
        </property>
        <property name="nas_password" label="nas服务器密码" default="" description="nas服务器密码">
        </property>
        <property name="nas_sourcePath" label="nas文件夹路径" default="" description="nas文件夹路径">
        </property>
    </group>
    
    <group id="file_storage_config" label="文件存储方式配置">
    <property name="file_storage_way" label="文件存储方式" default="fileoperation">
        <validator type="select">
            <option value="fileoperation" label="存储在服务器本地" related="file_local_config"></option>               
            <option value="fastdfsoperation" label="存储在FASTDFS" related="fastdfs_config"></option>     
        </validator>
    </property>
    <property name="file_temp_path" label="档案文件临时目录路径" default="/usr/local/temparchivefiles/yyyyMMdd">
    </property>
    </group>
     <group id="file_local_config" label="文件存储本地配置">
    	<property name="file_local_path" label="文件存储路径配置" default="/usr/local/archivefiles/yyyyMMdd" description="文件存储路径配置">
        </property>
        <property name="file_local_video_path" label="视频存储路径配置" default="/usr/local/archivevediofiles/yyyyMMdd" description="视频存储路径配置">
        </property>
    </group>
    <group id="fastdfs_config" label="FASTDFS配置">
        <property name="fastdfs_video_group" label="fastdfs视频存储组名" default="group1" description="FASTDFS视频存储组名">
        </property>
        <property name="fastdfs_other_group" label="fastdfs文件存储组名" default="group1" description="FASTDFS文件存储组名">
        </property>
        <!--
        <property name="fastdfs_host" label="fastdfs服务器地址" default="" description="fastdfs服务器地址">
        </property>  
        <property name="fastdfs_maxConn" label="fastdfs最大连接数" default="" description="fastdfs最大连接数">
        </property>
        <property name="fastdfs_maxIdle" label="fastdfs最大空闲连接数" default="" description="fastdfs最大空闲连接数">
        </property>
        <property name="fastdfs_maxBusyTime" label="fastdfs对象等待超时时间" default="" description="fastdfs对象等待超时时间">
        </property>
        -->
    </group>
    
    <group id="arch_grouping" label="档案分组配置">
         <property name="is_start_grouping" label="是否启用档案分组" default="1" description="是否启用档案分组">
         	<validator type="checkbox">
                 <option label="是" value="1"></option>
	
                 <option label="否" value="0"></option>
           	</validator>
         </property>
     </group>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/witness/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

	<group label="机构配置">
		<property name="witness_agent_pic_type" label="代理人证件照片类型(从档案模块查询,中间逗号隔开)" description="代理人身份证:正面[6E],反面[6F],头像[81].一事一授权委托书[61])" default="6E,6F,81,61">
			<validator type="required" />
		</property>
		<property name="main_agency_pic_type" label="主要身份证明文件类型(从档案模块查询,中间逗号隔开)" description="工商营业执照[64],社团法人登记证正本[96],社团法人登记证副本[97],事业法人登记证正本[98],事业法人登记证副本[99],机关法人成立批文正本[9A],机关法人成立批文副本[9B],统一社会信用代码正本[9C],统一社会信用代码副本[9D])" default="64,96,98,9A">
			<validator type="required" />
		</property>
		<property name="assist_agency_pic_type" label="辅助身份证明文件类型(从档案模块查询,中间逗号隔开)" description="组织机构代码证[32],税务登记证[33])" default="32,33">
			<validator type="required" />
		</property>
		<property name="witness_transactor_pic_type" label="双人见证上传档案类型(从档案模块查询,中间逗号隔开)" description="见证人与经办人合照[9E],工作人员与经办人合照[9F]" default="9E,9F">
			<validator type="required" />
		</property>
		<property name="witness_agent_default_pic_type" label="代理人开户机构资料页面默认加载的图片类型(从档案模块查询,中间逗号隔开)" description="法人身份证：正面[6K],反面[6L]、经办人身份证:正面[6G],反面[6H]、经办人头像[84]、法定代表人证明书[65]、授权委托书[30]" default="6K,6L,6G,6H,84,65">
			<validator type="required" />
		</property>
		<property name="witness_corporation_default_pic_type" label="法人开户默认加载的图片类型(从档案模块查询,中间逗号隔开)" description="法人身份证：正面[6K],反面[6L]、经办人身份证:正面[6G],反面[6H]、经办人头像[84]、法定代表人证明书[65]" default="6K,6L,6G,6H,84,65">
			<validator type="required" />
		</property>
		<property name="witness_survey_if_pic" label="问卷回访是否增加拍照上传" description="选择是,问卷回访需要增加拍照上传 " default="false">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_risk_type" label="风险测评试卷类型(从风险测评模块查询)" default="1">
			<validator type="required" />
		</property>
		<property name="witness_survey_type" label="问卷回访类型(从风险测评模块查询)" default="R">
			<validator type="required" />
		</property>
		<property name="witness_agreements_type" label="账户设置页面的协议编号(从协议模块查询,中间逗号隔开)" default="101">
			<validator type="required" />
		</property>
		<property name="witness_anti_money _risk_level" label="默认反洗钱风险等级" description="0:黑名单等级 1:高风险等级 2:中风险等级 3:低风险等级（更改了柜台反洗钱风险等级字典的券商，按已配置的值填写）" default="3">
			<validator type="required" />
		</property>
		<property name="witness_model_no" label="模板编号" default="25">
			<validator type="required" />
		</property>
		<property name="sms_content_witness_verify_success" label="审核通过短信提示" default="" description="审核通过短信提示(超过短信内容发送字数限制的部分不会发送)">
        </property>
        <property name="sms_content_witness_open_fail" label="开户失败短信提示" default=""
            description="开户失败短信提示, 请勿修改。示例：尊敬的客户，您在证券网上开户的申请未能通过，如有疑问请拨打客服热线400********。(超过短信内容发送字数限制的部分不会发送)">
        </property>
        <property name="sms_content_witness_open_success" label="开户成功短信提示"
            default=""
            description="开户成功短信提示, 其中{0}等是占位变量, 请勿修改。示例：尊敬的{0}，您好！感谢您开户，您的账户目前{1}。若需相关咨询，请拨打财通证券客服电话400********，恭祝您投资顺利！(超过短信内容发送字数限制的部分不会发送)">
        </property>
        <property name="witness_op_entrust_way" label="见证机构开户委托方式" default="O" description="默认委托方式是大O（离柜委托）">
			<validator type="required" />
		</property>
		<property name="witness_arch_image_sync" label="档案同步到柜台" default="9E,9F,84,64" description="配置需要同步到柜台的档案类型">
			<validator type="required" />
		</property>
		 <property name="witness_if_query_gem" label="是否在账户选择页面询问开通创业板" description="当前配置项选择为是,下面2个配置不生效,以此配置为主（仅在选择深圳A股时触发）" default="true">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_if_open_gem_by_default" label="是否默认开通创业板" description="询问是否开通创业板的选项为否,当前配置项才会生效（优先级低于弹窗选择创业板）" default="true">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_if_show_gem" label="是否在账户选择页面提示用户会开创业板" description="询问是否开通创业板的选项配置为否并且默认开通创业板为是,才会弹框提示用户会开通创业板" default="false">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_if_cancel_electronic_contract" label="是否在账户选择页面取消电子合同选项" description="选择是,账户选择页面、开户查询详情页面、结果页不显示电子合同选项" default="false">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_if_cancel_onsite_funds" label="是否取消上海场内基金、深圳场内基金" description="选择是,账户选择页面、开户查询详情页面、结果页不显示场内基金，也不去开场内基金" default="false">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_holder_info_if_required" label="控股股东是否去掉非必填字样" description="机构资料填写页面控股股东信息是否去掉非必填字样" default="false">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_shdc_business_code" label="行业代码字典项" default="11002" description="同柜台行业代码字典项,目前开源和东北是11002,其他券商11006">
			<validator type="required" />
		</property>
		<property name="witness_shdc_instrepr_type" label="法人类别字典项" default="1210" description="同柜台法人类别字典项,目前开源11002,其他券商是1210">
			<validator type="required" />
		</property>
		<property name="witness_shdc_company_type" label="企业类别字典项" default="11008" description="同柜台企业类别字典项,目前开源11002,其他券商11008">
			<validator type="required" />
		</property>
		<property name="witness_sms_params" label="调用第三方短信接口时配置的营业部的参数值" default="" description="调用第三方短信接口时配置的营业部的参数值">
		</property>
		<property name="witness_front_webAddr" label="集中运营平台使用此链接访问见证机构开户前台" default="" description="集中运营平台使用此链接访问见证机构开户前台">
		</property>
		<property name="witness_if_need_account" label="是否需要选择账户" description="选择是,账户选择页面、必须选择账户才能下一步" default="true">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="witness_transactor_id_verify" label="是否对经办人进行公安认证" description="开户见证方式是双人见证时，审核端操作员是否对经办人进行公安认证" default="true">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="suit_front_webAddr" label="适当性系统前台" default="" description="机构见证开户适当性双录时对接适当性系统前台">
		</property>
		<property name="suit_double_record" label="是否需要做适当性双录" description="默认不做适当性双录，如果需要做双录需要配置适当性前台地址" default="false">
			<validator type="select">
				<option value="true" label="是" />
				<option value="false" label="否" />
			</validator>
		</property>
		<property name="suit_prod_code" label="产品/服务编号" default="" description="适当性双录时的产品/服务编号">
		</property>
	</group>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/mail/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

    <property name="mail_server_host" label="邮件服务器主机" default="" description="邮件服务器IP或域名">
        <validator type="required" />
        <validator type="host" />
    </property>
    <property name="mail_server_port" label="邮件服务器端口" default="25">
        <validator type="required" />
        <validator type="range" value="[1,65535]" />
    </property>
    <property name="mail_server_auth" label="邮件服务器是否需要身份验证" default="true">
        <validator type="checkbox">
            <option value="true" label="是" />
            <option value="false" label="否" />
        </validator>
    </property>
    <group id="mail_server_auth_true">
        <property name="mail_server_username" label="邮件服务器登录用户名" default="">
        </property>
        <property name="mail_server_password" id="password" label="邮件服务器登录密码" default="">
        </property>
    </group>
    <property name="mail_send_from" label="邮件发送方邮箱" default="" description="邮件发送方邮箱">
        <validator type="required" />
        <validator type="email" />
    </property>
    <group id="mail_content" label="邮件内容">
        <property name="mail_content_bind" label="邮箱绑定" default=""
            description="邮箱绑定。示例：尊敬的客户您好。\n\t请点击http://obh.zhsec.com/my_info/mail_validate/?mailCode={0}\n\t该连接的有效期为1个小时，请在一个小时之内进行邮箱验证。谢谢。">
        </property>
    </group>
</config>
