=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hundsun.com/ooas/config"
    xmlns="http://www.hundsun.com/ooas/config" elementFormDefault="qualified">

    <xs:element name="config" type="config">
    </xs:element>

    <xs:complexType name="option">
        <xs:attribute name="value" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="related" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="validator">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="option" type="option"></xs:element>
        </xs:choice>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="select"></xs:enumeration>
                    <xs:enumeration value="radio"></xs:enumeration>
                    <xs:enumeration value="checkbox"></xs:enumeration>
                    <xs:enumeration value="required"></xs:enumeration>
                    <xs:enumeration value="url"></xs:enumeration>
                    <xs:enumeration value="email"></xs:enumeration>
                    <xs:enumeration value="date"></xs:enumeration>
                    <xs:enumeration value="digits"></xs:enumeration>
                    <xs:enumeration value="equalTo"></xs:enumeration>
                    <xs:enumeration value="extension"></xs:enumeration>
                    <xs:enumeration value="maxlength"></xs:enumeration>
                    <xs:enumeration value="minlength"></xs:enumeration>
                    <xs:enumeration value="rangelength"></xs:enumeration>
                    <xs:enumeration value="range"></xs:enumeration>
                    <xs:enumeration value="max"></xs:enumeration>
                    <xs:enumeration value="min"></xs:enumeration>
                    <xs:enumeration value="pattern"></xs:enumeration>
                    <xs:enumeration value="ipv4"></xs:enumeration>
                    <xs:enumeration value="ipv6"></xs:enumeration>
                    <xs:enumeration value="ip"></xs:enumeration>
                    <xs:enumeration value="domain"></xs:enumeration>
                    <xs:enumeration value="host"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="value" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="property">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="default" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="display">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                    <xs:enumeration value="hide"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="group">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
            <xs:element ref="property"></xs:element>
            <xs:element ref="group"></xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="label" type="xs:string"></xs:attribute>
        <xs:attribute name="description" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
        <xs:attribute name="display">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                    <xs:enumeration value="hide"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="define">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"></xs:enumeration>
                    <xs:enumeration value="false"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="validator" type="validator"></xs:element>
    <xs:element name="property" type="property"></xs:element>
    <xs:element name="group" type="group"></xs:element>

    <xs:complexType name="config">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="validator"></xs:element>
            <xs:element ref="property"></xs:element>
            <xs:element ref="group"></xs:element>
        </xs:choice>
    </xs:complexType>

</xs:schema>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/wt/config_xdt.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

<!-- 小贷通模块配置修改（洋洋，孙文帅） -->
	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="judge_checkbox2" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	<validator id="visible_checkbox" type="checkbox">
		<option label="显示" value="visible"></option>
		<option label="隐藏" value="invisible"></option>
	</validator>
	
	<group id="xdt" label="股票质押（小额贷）" display="true">
		<property name="system_name_xdt" label="小额贷系统命名" default="小贷通"
			description="" />
		<property name="xdt_risk_limit_score_name" label="风险评测阀值"
			default="0#默认型" description="风险评测阀值：0:默认型，1：保守型，2：稳健型，3：积极型，4：激进型，配置如：0#默认型" />

		<property name="xdt_max_borrow_money" label="券商对线上业务的最大借款金额限制"
			default="5000000#5000000#5000000" description="配置项有三种，融资打新、融资可用、融资可取，中间以#号隔开，配置如：5000000#5000000#5000000" />

		<property name="xdt_open_permission" label="小贷通权限配置，需要开通的权限"
			default="o\#a\#b"
			description="开通的权限:a:融资可取 b:融资可用，例如：o#a#b，即开通o和a和b的三个权限，开几个配几个，用#隔开，配置如：o\#a\#b" />

		<property name="xdt_credit_paper_type" label="小贷通征信问卷配置"
			default="k#k#k"
			description="打新（k），可取（l），可用（m） 如果打新可取可用三个试卷只需要做一次，则此处只能配置为 k#k#k，并且三种试卷类型的试题必须设置一模一样" />

		<property name="xdt_business_show" label="借款用途与征信管理显示哪几个功能"
			default="#1#1" description="分别为打新，可取，可用，用#号隔开：1为显示，0为不显示，如果只显示打新，示例：1#0#0" />

		<property name="xdt_j_equal_klm" label="股票质押征信问卷是否要和小贷通融资打新，可取，可用三个试卷类型一致 "
			default="0"
			description="股票质押征信问卷是否要和小贷通融资打新，可取，可用三个试卷类型是否也要一致,如果股票质押的征信问卷j与打新，可取，可用三个试卷类型都一致">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="xdt_pledge_ratio" label="借款页面折算金额系数" default="1"
			description="借款页面，券商设置的系数，该系数为折算金额系数，如不需要则配1，该配置项取值范围为0~1，不能等于0；即（0＜xdt.pledge.ratio＜=1）">
			<validator type="range" value="[0,1]" />
		</property>
		<property name="xdt_differentiate_user_srpkind" label="股票质押期限利率是否区分市场 "
			default="1" description="">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
		<property name="xdt_open_digital" label="小贷通权限开通是否需要签署电子签名约定书 "
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="xdt_business_knowledge" label="开通小贷通是否需要要个人资料确认页 "
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="xdt_pledge_sign_trade_agreement" label="小贷通股票质押是否需要签署交易协议 "
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="xdt_show_user_enable_quota" label="借款页面是否显示用户可用授信额度 "
			default="1" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="xdt_add_pledge_multiple" label="小贷通补充质押，需要补充到警告履约保障比的倍数"
			default="1.2" description="如：1.2" />
		<property name="xdt_bussiness_time_start" label="小贷通办理业务开始时间"
			default="00:00" description="如：00:00" />
		<property name="xdt_bussiness_time_end" label="小贷通业务结束时间"
			default="23:59" description="如：23:59" />
		<property name="quota_relate_asset" label="股票质押额度是否与资产状况关联 "
			default="1" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="fund_usage_show" label="是否显示资金用途 " default="1"
			description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="xdt_per_age_limited" label="开通小贷通权限的最低年龄限制"
			default="18" description="" />
		<property name="xdt_min_asset" label="允许开通小贷通权限的最小资产值"
			default="0" description="" />
		<property name="xdt_borrow_period_mode" label="申请借款页面借款周期的显示形式"
			default="0" description="下拉框  0:radio，配置为如：0" />
		<property name="xdt_date_back_warn" label="还款提醒天数" default="2"
			description="单位：天" />

		<property name="xdt_mail_create" label="小贷通开通是否开通邮箱 "
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="xdt_mail_address" label="开通邮箱登陆地址"
			default="http://mail.wlzq.163.com" description="如：http://mail.wlzq.163.com" />
		<property name="xdt_mail_prikey" label="邮箱私钥"
			default="30820279020100300d06092a864886f70d0101010500048202633082025f02010002818100a519c82f1cae463267a0152f89deab50c4d1a4eee31b1d311f8a4d722ee09b531ad385e1d2849117ed53f5d39e0eb713d71c2b6a77e8bd38c5722e2284d61631d3d24694d975bd81896b7a6edd67dca2245a0f7066f41d962695b0b2b5a07bf4f13e45135d201b66c213030fa4a94be70f3f8c41c0b2557119534916997767c30203010001028181009436eb01704bfb74b09683ae63a4e442e40e1874e4a8a8b23ad05bea4faf0f81b1a9869d4df1f897745555709e8a334cba65ed8bed0da121600fbadefe457b31d5397f3f021dd4a6a92e4c0773228b32a316b1838420bc76d28eadaa8148430196deb2fc2cabc637252a20e2a7a5a9e85a14d43a116d7395f3ff0d5926bc3f41024100f5723844fc1e0782c55180cdf2386295a2d0523ad3bbc5d0e2ade194c9c991c4238c4d84442bdefcce88feae0eb6511d7fb59d46abba8e7e445ddf12d4fdda53024100ac332632b025ab21e3cce22f6f04d78d3254cca9f69565451e022d2f6af1b55999e3638d7681702796d15324c7868ec7fa16232a5d23af6fe7c2a124d3e5eed1024100e5436b8c047388507e3f43311bafcf66364ea080928632a08b1c2039fac26d85e82e85b9a673d4361035a6aeaecf5db5503534536ed533847e17b0e6c64cd841024100a15b2475e6bcc548f24e6fbb86ca00b91bea7e04dd3c4c32a1d5e445446ecd41f283322bc259b3a045204c4a707453a26b6306fc915df8ec613ced06b75003a1024100c07304303edc2afe1df18e442928f6663fcf5272843065119c15482be975e8e91213733516d7cd821ed2a0f141641246ba25e327676b3ff58e21a08a21628700"
			description="" />
		<property name="xdt_mail_product" label="邮箱企业标识" default="wlzq_163_com"
			description="如：wlzq_163_com" />
		<property name="xdt_mail_domain" label="邮箱域名" default="wlzq.163.com"
			description="如：wlzq.163.com" />
		<property name="xdt_mail_prefix" label="邮箱前缀" default="wlzq"
			description="密码前缀 邮箱初始密码：前缀+用户身份证号后六位,如：wlzq" />

		<property name="xdt_direct_open_permission" label="是否直接开通小贷通权限"
			default="1" description="打开表示直接调用接口增加小贷权限，关闭则需要柜台手动开通小贷权限">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
		<property name="xdt_max_credit_quota" label="小贷通最大授信额度"
			default="20000000" description="小贷通最大授信额度，单位：元，该配置为空时表示最大额度不设上限">
		</property>
		<property name="xdt_open_digital_sign" label="开通小贷若为签署电子签名约定书，是否直接签署"
			default="1" description="打开表示直接签署，关闭表示不签署并提示未签约电子签名约定书">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
		<property name="xdt_quota_relate_credit_asset" label="小贷通的授信额度是否关联信用资产" default="1" description="(@version:3.4.1;@auth:laidy)">
			<validator type="checkbox" ref="judge_checkbox2"></validator>
		</property>
		<property name="risk_satisfy_level" label="满足开通小贷通风险等级（高于保守型  ）"
			default="2#3#4"
			description="顶点柜台适用，满足开通小贷通风险等级（高于保守型  ） ：0:默认型，1：保守型，2：稳健型，3：积极型，4：激进型，示例：2#3#4" />
		<property name="stock_mortgage_min_balance" label="申请股票质押，要求资金账户最低余额"
			default="0" description="顶点柜台适用，示例：0" />
		<property name="stock_mortgage_satisfy_level" label="邮箱企业标识"
			default="20#21#22" description="顶点柜台适用，满足开通小额贷的征信级别（大于C）,示例：20#21#22" />
		<property name="fund_usage_dx" label="小贷通融资打新股票质押资金用途"
			default="太融易-小额股票质押融资申购" />
		<property name="xdt_risk_age_need" label="是否在风险评测页面提示用户年龄过大" default="false"></property>
		<property name="xdt_risk_warn_age" label="用户年龄超过多少提示" default="70"></property>
		<property name="xdt.cancel.lation.time" label="小贷通股票质押可撤单时间" default="" description="小贷通股票质押可撤单时间，为空表示没有时间限制（默认为空）#示例:xdt.cancel.lation.time=09:30-15:00"></property>
		
		<property name="xdt_borrow_record_show_addPledge" label="借款记录是否始终显示补充质押按钮 " default="0"
			description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		
		<property name="xdt_add_pledge_show_addMoney" label="补充质押页面是否显示至少补充多少钱 ，并且是否限制至少补充该钱数" default="1"
			description="交易系统如果为06，则建议打开，交易系统如果为UF，暂时建议不打开，因为UF的钱数算法暂时还没确定，可能该钱数不对">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	</group>

</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/video/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

	<group label="视频配置">
		<property name="videoswitch_queue_addr" label="视频服务IP" default="127.0.0.1">
			<validator type="required" />
			<validator type="host" />
		</property>
		<property name="videoswitch_queue_port" label="视频服务端口" default="8906">
			<validator type="required" />
			<validator type="range" value="[1,65535]" />
		</property>
		<property name="videoswitch_queue_type" label="视频服务http类型" default="http">
           		<validator type="radio">
               		<option label="http" value="http"></option>
               		<option label="https" value="https"></option>
           		</validator>
       	</property>
		<property name="videoswitch_connectInnerIpFlag" label="坐席端通过内网连接视频服务器标志" default="false"
		description="如果不配置此项默认通过外网ip连接视频流服务器">
			<validator type="checkbox">
				<option label="内网" value="true"></option>
				<option label="外网" value="false"></option>
			</validator>
		</property>
		<property name="video_auto_assign" label="是否自动分配客户" default="0"
			description="开启后自动分配任务给坐席，且抢答模式失效">
			<validator type="checkbox">
				<option label="是" value="1"></option>
				<option label="否" value="0"></option>
			</validator>
		</property>
		<property name="video_auto_assign_timeout" label="坐席未接自动分配任务超时时间(秒)" default="5"
			description="超过配置时间，任务将被分配给下一个坐席">
			<validator type="range" value="[1,65535]" />
		</property>
		<property name="video_view_model" label="视频显示模式" default="0"
		description="0：默认模式；1：重叠模式；2：缩小模式；3：平铺模式；4：动态模式；模式效果见：http://bbs.anychat.cn/forum.php?mod=viewthread&amp;tid=1071.">
			<validator type="required" />
		</property>
		<property name="video_capture_model" label="立即处理预抢答模式" default="0"
			description="自动分配客户关闭时才有效">
			<validator type="checkbox">
				<option label="打开" value="1"></option>
				<option label="关闭" value="0"></option>
			</validator>
		</property>
		<property name="videoswitch_isVideoPlay" label="是否需要回放视频" default="true"
		  description="当配置为true时:视频验证需要回放视频才可到下一步，当配置为false时，不用回放视频就能到下一步"
		>
		    <validator type="checkbox">
				<option label="开" value="true"></option>
				<option label="关" value="false"></option>
			</validator>
		</property>
		<property name="video_upload_async" label="视频异步上传" default="false"
		description="当配置true时:录像上传与视频分离，当配置false时，录像上传只能在视频过程中上传">
			<validator type="checkbox">
				<option label="开" value="true"></option>
				<option label="关" value="false"></option>
			</validator>
		</property>
		<property name="video_successAndUpload" label="验证通过并补传视频" default="false"
		description="当配置true时:显示验证通过并补传视频按钮，当配置false时，不显示显示验证通过并补传视频按钮">
			<validator type="checkbox">
				<option label="开" value="true"></option>
				<option label="关" value="false"></option>
			</validator>
		</property>
		<property name="video_upload_timeout_mins" label="视频异步上传时用户视频步骤超时设置（分钟）" default="6"
		description="当配置视频异步上传=true时，此配置生效；用户前端的请求时间-视频结束录制时间>此超时设置，则默认用户需重新进入视频环节"></property>
		<property name="video_record_leastTime" label="后台坐席视频录制最短时间" default="5">
			<validator type="required" />
		</property>
		<property name="video_isSelfOrg_waitPosition" label="用户排队位置是否为自己所在营业部排队位置" default="false"
		description="当配置true时:显示用户所在营业部的排队位置，当配置false时，显示所有营业部总的排队位置">
			<validator type="checkbox">
				<option label="开" value="true"></option>
				<option label="关" value="false"></option>
			</validator>
		</property>
	    <property name="video_client_leasttime" label="坐席接通视频超时时间（秒）" />
		<property name="video_show_words" label="是否显示话术" default="false">
			<validator type="checkbox">
				<option label="是" value="true"></option>
				<option label="否" value="false"></option>
			</validator>
		</property>
		<property name="need_login_video_queue_monitor" label="视频队列监控页面是否需要登陆" default="true">
			<validator type="checkbox">
				<option label="是" value="true"></option>
				<option label="否" value="false"></option>
			</validator>
		</property>
	</group>
	<group label="AnyChat配置">
		<property name="anyChatStreamIpInner" label="视频内网服务器IP" default="127.0.0.1">
			<validator type="required" />
			<validator type="host" />
		</property>
		<property name="anyChatStreamIpOut" label="视频外网服务器IP" default="127.0.0.1">
			<validator type="required" />
			<validator type="host" />
		</property>
		<property name="anyChatStreamPort" label="视频服务器端口" default="8906">
			<validator type="required" />
			<validator type="range" value="[1,65535]" />
		</property>
		<property name="anychat_version" label="anychat版本" description="集群版需要anychat 6.2以上版本" default="v5_2">
			<validator type="select">
	            <option label="5.2" value="v5_2"></option>
	            <option label="6.2" value="v6_2"></option>
	            <option label="6.3" value="v6_3"></option>
	        </validator>
		</property>
		<property name="anychat_group_flag" label="是否为集群版" description="集群版需要anychat 6.2及以上版本" default="false">
			<validator type="checkbox">
	            <option label="是" value="true"></option>
	            <option label="否" value="false"></option>
	        </validator>
		</property>
		<property name="anychat_app_guid" label="anychat集群版分配的appguid" />
		<property name="anychat_busin_server_standalone_mode" label="是否开启anychat业务服务器独立模式" description="如果是，那么视频组件通过xpe-sisap-video-anychat连接anychat。如果否
		，视频组件直连anychat" default="false">
			<validator type="checkbox">
	            <option label="是" value="true"></option>
	            <option label="否" value="false"></option>
	        </validator>
		</property>
	</group>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/db/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">
    <property name="xpe_default_system_subsysno" label="后台管理默认使用系统编号" default="1">
        <validator type="required" />
    </property>
    <property name="db_driverClass" label="数据库驱动类" default="oracle.jdbc.driver.OracleDriver" display="hide">
        <validator type="required" />
    </property>
    <property name="db_jdbcUrl" label="数据库连接串URL" default="jdbc\:oracle\:thin\:@10.10.16.150\:1521\/wskhtest" description="格式：jdbc\:oracle\:thin\:@ip\:port\/servicename">
        <validator type="required" />
    </property>
    <property name="db_username" label="数据库连接用户名" default="wskh_product_32">
        <validator type="required" />
    </property>
    <property name="db_password" id="password" label="数据库连接密码" default="wskh">
        <validator type="required" />
    </property>
    
    <property name="crm_db_driverClass" label="财富crm数据库驱动类" default="com.microsoft.sqlserver.jdbc.SQLServerDriver" display="hide">
        <validator type="required" />
    </property>
    <property name="crm_db_jdbcUrl" label="财富crm数据库连接串URL" default="jdbc:sqlserver://localhost:1433;databasename=cfzq_com" description="格式：jdbc\:oracle\:thin\:@ip\:port\/servicename">
        <validator type="required" />
    </property>
    <property name="crm_db_username" label="财富crm数据库连接用户名" default="sa">
        <validator type="required" />
    </property>
    <property name="crm_db_password" id="password" label="财富crm数据库连接密码" default="sa">
        <validator type="required" />
    </property>
    
    <property name="db_mot_driverClass" label="东北MOT数据库驱动类" default="oracle.jdbc.driver.OracleDriver" display="hide">
		<validator type="required" />
	</property>
	<property name="db_mot_jdbcUrl" label="东北MOT数据库连接串URL" default="jdbc\:oracle\:thin\:@10.10.16.150\:1521\/wskhtest" description="格式：jdbc\:oracle\:thin\:@ip\:port\/servicename">
		<validator type="required" />
	</property>
	<property name="db_mot_username" label="东北MOT数据库连接用户名" default="wskh_product_32">
		<validator type="required" />
	</property>
	<property name="db_mot_password" id="password" label="东北MOT数据库连接密码" default="wskh">
		<validator type="required" />
	</property>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/risk/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

    <group id="risk_config" label="问卷相关配置">
        <property name="examrisk_autofill" label="风险评测是否自动填充" default="false" description="风险评测自动填充你年龄, 职业，学历题目的答案">
			<validator type="checkbox">
				<option label="是" value="true"></option>
				<option label="否" value="false"></option>
			</validator>
		</property>
		<property name="examrisk_hiddenexam" label="风险评测自动填充的题目是否隐藏" default="false" description="风险评测为自动填充才生效">
			<validator type="checkbox">
				<option label="开" value="true"></option>
				<option label="关" value="false"></option>
			</validator>
		</property>
		<property name="risk_age_options" label="年龄区间及对应选项id " default="" description="格式为[年龄区间下限,年龄区间上限]=选项号:[年龄区间下限,年龄区间上限]=选项号，例如: [0,30]=1:[31,40]=2:[41,50]=3:[51,60]=4:[61,999]=5  ， 需要与问卷题目选项一致，风险评测为自动填充才生效">
			
		</property>
		<property name="risk_job_options" label="职业区间及对应选项id " default="" description="格式为[字典子项1,字典子项2,字典子项n]=选项号:[字典子项1,字典子项2,字典子项n]=选项号，需要与问卷题目选项及数据字典1015配置一致 ，风险评测为自动填充才生效">
			
		</property>
		<property name="risk_degree_options" label="学历区间及对应选项id " default="" description="格式为[字典子项1,字典子项2,字典子项n]=选项号:[字典子项1,字典子项2,字典子项n]=选项号，需要与问卷题目选项及数据字典1014配置一致 ，风险评测为自动填充才生效">
			
		</property>
		<property name="risk_degree_trans" label="学历的选项ID对应修改的学历字典值" default="" description="格式为 选项号=字典子项:选项号=字典子项，需要与问卷题目选项及数据字典1014配置一致 ，风险评测为自动填充，并且配置了学历区间及对应选项id后，才生效">
			
		</property>
		
    </group>
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/src/main/resources/configure/wt/config_rights.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">

<!-- 权限类配置 -->
	<validator id="judge_checkbox" type="checkbox">
		<option label="开" value="1"></option>
		<option label="关" value="0"></option>
	</validator>
	<validator id="judge_checkbox2" type="checkbox">
		<option label="需要" value="1"></option>
		<option label="不需要" value="0"></option>
	</validator>
	<validator id="display_checkbox" type="checkbox">
		<option label="显示" value="1"></option>
		<option label="隐藏" value="0"></option>
	</validator>
	
	
	<!-- 退市整理配置 -->
	<group id="delistFinishing" label="退市整理配置" display="true">
	 <property name="delist_zd_trade_right" label="退市整理股票业务，开通是否是否要判断交易权限满2年" default="0"
	  description="退市整理股票业务，开通的是否是否要判断股票交易权限满2年。1 需要判断，0 不需要判断。默认0">
	  <validator type="checkbox" ref="judge_checkbox2"></validator>
	  </property>
	 <property name="delist_security_market_value" label="退市整理股票业务，开通是否是否要判断资产市值满50W" default="0" 
	  description="退市整理股票业务，开通的是否是否要判断普通资产满50W,1 需要判断，0 不需要判断。默认0">
	 <validator type="checkbox" ref="judge_checkbox2"></validator>
	 </property>	
	</group>
	
	<!-- 委托方式配置 -->
	<group id="consign_type" label="委托方式配置" display="true">
		<property name="entruts_show_risktip" label="是否需要显示委托方式开通后风险提示"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="entruts_risktip_href" label="委托方式风险警示地址"
			default="" description="如配置不需要开通后风险提示，此项无需配置" />
		<property name="entruts_open_need_cert" label="开通委托方式 是否要检测证书" default="0"
			description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
		<property name="entrust_can_cancel" label="是否需要取消委托方式功能"
			default="0" description="">
			<validator type="checkbox" ref="judge_checkbox"></validator>
		</property>
	</group>
	
</config>

=== 15207126400/Product-SSM/yw-framework/yw-context-config/target/classes/configure/ant/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.hundsun.com/ooas/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hundsun.com/ooas/config ../config.xsd">
	<group name="InterFaceConfig" label="蚂蚁金服接口服务">
		<property name="ant_http_url" label="接口服务地址" default="">
		</property>
		<property name="ant_app_id" label="对端系统编号" default="">
		</property>
		<property name="ant_sign_publickey" label="签名加密解密公钥" default="">
		</property>
		<property name="interface_function_name" label="回调接口定义" default="">
		</property>
		<property name="ant_version_id" label="回调接口版本号" default="">
		</property>
		<property name="ant_open_foundaccount_defaultcode" label="开设基金账户默认编号"
			default=""></property>

		<property name="ant_protocol_defaultcode" label="默认签署开户协议编号"
			default="" description="多个协议编号用逗号分隔">
		</property>
		
		<property name="ant_risk_papertype" label="蚂蚁金服风险测评paper_type类型" default="">
		</property>
		
		<property name="ant_wskh_appid" label="蚂蚁金服接入APPID" default=""/>
	</group>

	<group name="SFTPConfig" label="SFTP服务配置">
		<property name="sftp_http_url" label="SFTP服务地址" default="">
		</property>
		<property name="sftp_http_port" label="SFTP服务端口号" default="">
		</property>
		<property name="sftp_user_name" label="用户名" default="">
		</property>
		<property name="sftp_password" label="密码" default="">
		</property>
		<property name="sftp_filepath" label="文件下载目录" default=""  description="例如：/download/cairenhui/">
		</property>
	</group>

	<group name="WSKHRSAConfig" label="网开RSA加密解密公钥私钥">
		<property name="wskh_sign_publickey" label="RSA公钥" default="">
		</property>
		<property name="wskh_sign_privatekey" label="RSA私钥" default="">
		</property>
	</group>
</config>
